# Generated by Django 3.2.6 on 2021-11-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('booktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Textbook', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Novels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('novelcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Novels', to='main.category')),
            ],
        ),
    ]
