# Generated by Django 3.2.6 on 2021-11-18 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novels',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 21, 7, 48, 277363)),
        ),
        migrations.AddField(
            model_name='novels',
            name='pages',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='novels',
            name='price',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='textbook',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 21, 7, 48, 274391)),
        ),
        migrations.AddField(
            model_name='textbook',
            name='pages',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='textbook',
            name='price',
            field=models.IntegerField(default=400),
        ),
    ]
