# Generated by Django 3.2.6 on 2021-11-18 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211118_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novels',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 18, 14, 36, 372225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 18, 14, 36, 369230, tzinfo=utc)),
        ),
    ]
